version: '3.3'
services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306" 
     environment:
       MYSQL_ROOT_PASSWORD: sometodo
       MYSQL_DATABASE: todo
       MYSQL_USER: todo
       MYSQL_PASSWORD: todo
   app:
     depends_on:
       - db
     image: maetaku/todo:latest
     ports:
       - "3000:3000"
     restart: always
     environment:
        MYSQL_DB_HOST: db:3306
        MYSQL_DB_USER: todo
        MYSQL_DB_PASSWORD: todo
        MYSQL_DB_NAME: todo
volumes:
    db_data: {}

